cookie:
  expiry_days: 7
  key: some_key
  name: some_cookie_name
credentials:
  usernames:
    liqh:
      email: qinghao.li@dhc.com.cn
      failed: '3'
      failed_login_attempts: '3'
      logged_in: false
      name: "\u674E\u6176\u8C6A"
      password: $2b$12$br5g48Ia8I7A6rmQke6JN.Ubd6p9s0qx.pIKWmamDDfu1S3nHY95K
      role: admin
    wangcy:
      email: chuyun.wang@dhc.com.cn
      failed_login_attempts: '3'
      logged_in: false
      name: "\u738B\u695A\u97FB"
      password: $2b$12$sK2tYAiEymGHWhnbjf3q/uG/S3SUPF0XAN2bkJNpvOTIKCYo11sYG
      role: admin
    wangys:
      email: yongsheng.wang@dhc.com.cn
      failed_login_attempts: '3'
      logged_in: true
      name: "\u738B\u6C38\u76DB"
      password: $2b$12$/L8DxLeQEDlXWx06Bsuktui9Yih/pXEW6U1M/qohbYnIAg9rpcv3O
      role: admin
    zhaojq:
      email: jiaqi2.zhao@dhc.com.cn
      failed_login_attempts: '3'
      logged_in: false
      name: "\u8D99\u5609\u742A"
      password: $2b$12$YY99ihrR0rmWsWm8aECbpO3c8aBszCi52t45rDCul.3MoH21pgKQG
      role: user
pre-authorized:
  emails:
  - melsby@gmail.com
