cookie:
  expiry_days: 7
  key: some_key
  name: some_cookie_name
credentials:
  usernames:
    liqh:
      email: qinghao.li@dhc.com.cn
      failed_login_attempts: '9'
      logged_in: false
      name: "\u674E\u6176\u8C6A"
      password: $2b$12$zYwXx5z49bkHEt8NW7qUEOpFoMM7PGVkGdPRKo5oTxTrdb7xSXQQq
      role: admin
    wangcy:
      email: chuyun.wang@dhc.com.cn
      failed_login_attempts: '3'
      logged_in: false
      name: "\u738B\u695A\u97FB"
      password: $2b$12$xZhyVh7s4GEPlHSp5B10de4a5rV3YljwaoA8CPWUdLSJJboQW5rrW
      role: admin
    wangys:
      email: yongsheng.wang@dhc.com.cn
      failed_login_attempts: '3'
      logged_in: true
      name: "\u738B\u6C38\u76DB"
      password: $2b$12$XmrEt6F8Fgxe7j9ul0BuyeaFldU0mlfrZTNBFFrRAWge56rdK2p7.
      role: admin
    zhaojq:
      email: jiaqi2.zhao@dhc.com.cn
      failed_login_attempts: '3'
      logged_in: false
      name: "\u8D99\u5609\u742A"
      password: $2b$12$pS4SP9v0Tgz3byEzXSgQY.UrrcnPqaRVdW36NKtjqEMNYYraq0wWG
      role: user
pre-authorized:
  emails:
  - melsby@gmail.com
